<?php

namespace Database\Seeders;

use App\Models\Associado;
use Illuminate\Database\Seeder;

class AssociadoSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        $associados = [
            [
                'NomeCompleto' => 'Maria Oliveira Silva',
                'NumeroDocumento' => '12345678909',
                'Email' => 'maria.oliveira@email.com',
                'Telefone' => '61999998888',
                'DtNascimento' => '1990-05-20',
                'Cep' => '70000000',
                'Endereco' => 'Rua das Flores',
                'Numero' => '123',
                'Complemento' => 'Apto 101',
                'Bairro' => 'Centro',
                'Cidade' => 'Brasília',
                'Uf' => 'DF',
                'Motivo' => 'Desejo participar da associação e contribuir com a comunidade.',
                'Status' => 'Aprovado',
                'IsConsentimentoLgpd' => true,
                'Origem' => 'site',
                'Observacao' => 'Associado ativo desde o início.',
            ],
            [
                'NomeCompleto' => 'João Pedro Santos',
                'NumeroDocumento' => '98765432100',
                'Email' => 'joao.santos@email.com',
                'Telefone' => '61988887777',
                'DtNascimento' => '1985-08-15',
                'Cep' => '71000000',
                'Endereco' => 'Avenida Principal',
                'Numero' => '456',
                'Complemento' => 'Casa',
                'Bairro' => 'Asa Norte',
                'Cidade' => 'Brasília',
                'Uf' => 'DF',
                'Motivo' => 'Interesse em fazer parte da organização.',
                'Status' => 'Pendente',
                'IsConsentimentoLgpd' => true,
                'Origem' => 'indicacao',
                'Observacao' => null,
            ],
            [
                'NomeCompleto' => 'Ana Carolina Ferreira',
                'NumeroDocumento' => '11122233344',
                'Email' => 'ana.ferreira@email.com',
                'Telefone' => '61977776666',
                'DtNascimento' => '1995-03-10',
                'Cep' => '72000000',
                'Endereco' => 'Quadra 10 Conjunto A',
                'Numero' => '789',
                'Complemento' => 'Bloco B Apto 201',
                'Bairro' => 'Taguatinga',
                'Cidade' => 'Brasília',
                'Uf' => 'DF',
                'Motivo' => 'Gostaria de colaborar com os projetos sociais.',
                'Status' => 'Aprovado',
                'IsConsentimentoLgpd' => true,
                'Origem' => 'site',
                'Observacao' => 'Participa ativamente dos eventos.',
            ],
            [
                'NomeCompleto' => 'Carlos Eduardo Lima',
                'NumeroDocumento' => '55566677788',
                'Email' => 'carlos.lima@email.com',
                'Telefone' => '61966665555',
                'DtNascimento' => '1988-12-25',
                'Cep' => '73000000',
                'Endereco' => 'Rua do Comércio',
                'Numero' => '321',
                'Complemento' => null,
                'Bairro' => 'Ceilândia',
                'Cidade' => 'Brasília',
                'Uf' => 'DF',
                'Motivo' => 'Quero ajudar a fortalecer a comunidade.',
                'Status' => 'Rejeitado',
                'IsConsentimentoLgpd' => true,
                'Origem' => 'evento',
                'Observacao' => 'Não atendeu aos requisitos mínimos.',
            ],
            [
                'NomeCompleto' => 'Juliana Costa Almeida',
                'NumeroDocumento' => '99988877766',
                'Email' => 'juliana.costa@email.com',
                'Telefone' => '61955554444',
                'DtNascimento' => '1992-07-18',
                'Cep' => '70100000',
                'Endereco' => 'SQN 210 Bloco H',
                'Numero' => '105',
                'Complemento' => 'Apto 302',
                'Bairro' => 'Asa Norte',
                'Cidade' => 'Brasília',
                'Uf' => 'DF',
                'Motivo' => 'Interesse em networking e desenvolvimento profissional.',
                'Status' => 'Pendente',
                'IsConsentimentoLgpd' => true,
                'Origem' => 'site',
                'Observacao' => null,
            ],
            [
                'NomeCompleto' => 'Roberto Mendes da Silva',
                'NumeroDocumento' => '33344455566',
                'Email' => 'roberto.mendes@email.com',
                'Telefone' => '61944443333',
                'DtNascimento' => '1980-11-05',
                'Cep' => '71900000',
                'Endereco' => 'Área Especial',
                'Numero' => '999',
                'Complemento' => 'Loja 5',
                'Bairro' => 'Águas Claras',
                'Cidade' => 'Brasília',
                'Uf' => 'DF',
                'Motivo' => 'Desejo expandir minha rede de contatos.',
                'Status' => 'Aprovado',
                'IsConsentimentoLgpd' => true,
                'Origem' => 'indicacao',
                'Observacao' => 'Empresário local muito ativo.',
            ],
            [
                'NomeCompleto' => 'Fernanda Rodrigues Souza',
                'NumeroDocumento' => '77788899900',
                'Email' => 'fernanda.rodrigues@email.com',
                'Telefone' => '61933332222',
                'DtNascimento' => '1998-02-28',
                'Cep' => '72100000',
                'Endereco' => 'QNM 40 Conjunto M',
                'Numero' => '15',
                'Complemento' => 'Casa 3',
                'Bairro' => 'Ceilândia Norte',
                'Cidade' => 'Brasília',
                'Uf' => 'DF',
                'Motivo' => 'Busco oportunidades de voluntariado.',
                'Status' => 'Pendente',
                'IsConsentimentoLgpd' => true,
                'Origem' => 'redes_sociais',
                'Observacao' => null,
            ],
            [
                'NomeCompleto' => 'Paulo Henrique Barbosa',
                'NumeroDocumento' => '22233344455',
                'Email' => 'paulo.barbosa@email.com',
                'Telefone' => '61922221111',
                'DtNascimento' => '1975-09-12',
                'Cep' => '70200000',
                'Endereco' => 'SQS 315 Bloco C',
                'Numero' => '208',
                'Complemento' => 'Apto 501',
                'Bairro' => 'Asa Sul',
                'Cidade' => 'Brasília',
                'Uf' => 'DF',
                'Motivo' => 'Aposentado buscando atividades sociais.',
                'Status' => 'Aprovado',
                'IsConsentimentoLgpd' => true,
                'Origem' => 'site',
                'Observacao' => 'Participa regularmente das reuniões.',
            ],
            [
                'NomeCompleto' => 'Patrícia Gomes Martins',
                'NumeroDocumento' => '66677788899',
                'Email' => 'patricia.gomes@email.com',
                'Telefone' => '61911110000',
                'DtNascimento' => '1993-04-22',
                'Cep' => '71800000',
                'Endereco' => 'Rua 12 Norte',
                'Numero' => '542',
                'Complemento' => null,
                'Bairro' => 'Águas Claras',
                'Cidade' => 'Brasília',
                'Uf' => 'DF',
                'Motivo' => 'Interesse em projetos educacionais.',
                'Status' => 'Pendente',
                'IsConsentimentoLgpd' => true,
                'Origem' => 'indicacao',
                'Observacao' => null,
            ],
            [
                'NomeCompleto' => 'Ricardo Alves Pereira',
                'NumeroDocumento' => '44455566677',
                'Email' => 'ricardo.alves@email.com',
                'Telefone' => '61900009999',
                'DtNascimento' => '1987-06-30',
                'Cep' => '72500000',
                'Endereco' => 'QNN 28 Área Especial',
                'Numero' => '100',
                'Complemento' => 'Sala 203',
                'Bairro' => 'Ceilândia Sul',
                'Cidade' => 'Brasília',
                'Uf' => 'DF',
                'Motivo' => 'Desejo contribuir com minha experiência profissional.',
                'Status' => 'Aprovado',
                'IsConsentimentoLgpd' => true,
                'Origem' => 'evento',
                'Observacao' => 'Palestrante convidado em eventos.',
            ],
        ];

        foreach ($associados as $associado) {
            Associado::create($associado);
        }

        $this->command->info('✅ 10 associados cadastrados com sucesso!');
    }
}