/**
 * Export centralizado de todas as constantes do Page Builder
 */

// Block Types Constants
export {
  BLOCK_CATEGORIES,
  BLOCK_LABELS,
  BLOCK_DESCRIPTIONS,
  CATEGORY_LABELS,
  CATEGORY_ICONS,
  FEATURED_BLOCKS,
  ADVANCED_BLOCKS,
} from './blockTypes';

// Default Config Constants
export {
  DEFAULT_EDITOR_CONFIG,
  DEFAULT_EDITOR_MODE,
  DEFAULT_BLOCK_CLASSES,
  RESPONSIVE_BREAKPOINTS,
  DEFAULT_GRID_CONFIG,
  DEFAULT_THEME_COLORS,
  DEFAULT_TYPOGRAPHY,
  DEFAULT_SPACING,
  DEFAULT_ANIMATION_CONFIG,
  VALIDATION_MESSAGES,
  IMAGE_UPLOAD_CONFIG,
  VIDEO_UPLOAD_CONFIG,
  KEYBOARD_SHORTCUTS,
  DEFAULT_PAGINATION,
} from './defaultConfig';